name: lyakhov_prac_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.9.2
dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^8.0.0
  go_router: ^14.2.0
  flutter_bloc: ^8.1.1
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+2
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^9.1.0

flutter:
  uses-material-design: true
